### ISSUE TITLE
save outfit

### ISSUE THREAD

**Issue by Tecktorious** [qbcore-redm-framework/qbr-clothing#18]
save button on outfit is not working not even recieving only use the outfit

**Comment by RexShack** [comment]
also get the same, when I change outfit and set you exit and you have not changed outfits

**Comment by ToniSevHD** [comment]
It is the third or fourth character that I create and applying outfits does not work for me. It just keeps them for me, but then when I go home to change my clothes, it won't let me apply outfits.

**Comment by RobWhitewick** [comment]
seems to be fixed with https://github.com/qbcore-redm-framework/qbr-clothing/pull/23#issue-1265710669
