### ISSUE TITLE
nil value for skinDetails

### ISSUE THREAD

**Issue by holylightservices** [qbcore-redm-framework/qbr-clothing#2]
on cl_main.lua line 155 the skinDetails has a nil value and the ui for clothing after character creation is not opening.

**Comment by Demo4889** [comment]
I get the same issue. haven't figured out how to fix it yet

**Comment by holylightservices** [comment]
fixed it. Just reworked the whole script

**Comment by Demo4889** [comment]
post the fix?

**Comment by saculator** [comment]
would love to grab this fix is you can send them

**Comment by BerkieBb** [comment]
It's fixed with the multicharacter update
