### ISSUE TITLE
server errors seen when player does not change default settings

### ISSUE THREAD

**Issue by RexShack** [qbcore-redm-framework/qbr-clothing#20]
see the following errors when a new player creates an account and keeps the default clothing/skin settings
also noticed in the database that the skin reference is not created for the associated player
character is unusable when these conditions are met
I did raise this in discord but got NIL response
![Screenshot_2022-04-26_200510](https://user-images.githubusercontent.com/76662933/166904886-6bcb4179-6c84-40e6-a0ee-d3bf4638bdfe.jpg)

**Comment by gononono64** [comment]
@RexShack We recently made some changes with clothing and multicharacter. Has your issue been resolved?

**Comment by RexShack** [comment]
thanks for resonding a year later but gave up on this framework a long time ago

**Comment by gononono64** [comment]
Ah yes my apologies. A group of us recently got invested in making thing work in the framework. Hopefully, once we get thing sorted you will try qbcore again. Thank you for your post.
