### ISSUE TITLE
Bug Face

### ISSUE THREAD

**Issue by dwiprizzy** [qbcore-redm-framework/qbr-clothing#27]
After re-logging .player face getting bugged or not load  , that make player crashing all the time

**Comment by joeyave201** [comment]
did you fix? [dwiprizzy](https://github.com/dwiprizzy)

**Comment by dwiprizzy** [comment]
nope @joeyave201  still searching for best solution to handle di bug

**Comment by DidrikxD** [comment]
Have the same problem, did you find a fix for this? @dwiprizzy

**Comment by Nick5M420** [comment]
this is still an issue has anyone figured this out?
