### ISSUE TITLE
Not saving skin in DB

### ISSUE THREAD

**Issue by Averdrity** [qbcore-redm-framework/qbr-clothing#28]
When creating a character after INTENSE modelling of the character with cloths included you finally press save and it takes you to another screen to choose your spawn point. You will fast see that your SKIN loaded to some default skin and then you spawn and also see that after that intense modelling its not saved.

I've tried for a few days now to fix the issue, but nothing I do works.
Lots of people having this issue.
It saves cloths but not skin. In the Database under "playerskins" the "skin" is empty. Rest of the table is filled correctly.

**Comment by gononono64** [comment]
@Averdrity We apologies for the wait. We have recently made changes to many resource. Has the issue since been resolved?
