### ISSUE TITLE
table expected, got nil

### ISSUE THREAD

**Issue by Andyauk** [qbcore-redm-framework/qbr-clothing#39]
`SCRIPT ERROR: @qbr-clothing/client/main.lua:49: bad argument #1 to 'for iterator' (table expected, got nil)`

seems to be trying to find cloth_hash_names as line 49 is `for _, v in pairs(cloth_hash_names) do` in the past it had that name in the file but now its not.

**Comment by DosKit** [comment]
Thanks for pointing that out that was a oversight. that whole section can be removed. https://github.com/qbcore-redm-framework/qbr-clothing/blob/92a572793b06aade60c03a0942b051bfbc20feba/client/main.lua#L48-L82

I did a PR on it should be fixed in a few days.

**Comment by Andyauk** [comment]
> Thanks for pointing that out that was a oversight. that whole section can be removed.
> 
> https://github.com/qbcore-redm-framework/qbr-clothing/blob/92a572793b06aade60c03a0942b051bfbc20feba/client/main.lua#L48-L82
> 
> I did a PR on it should be fixed in a few days.

thanks
