### ISSUE TITLE
Menu closes on Keypress

### ISSUE THREAD

**Issue by Milkbottle98** [qbcore-redm-framework/qbr-clothing#43]
Hey,

when i press a key while the menu is open it bugs out, closes  and my mouse is buggy on the screen. The Game doesnt react to my actions after that.

Thanks

**Comment by IDKFORCE** [comment]
hello we have fix this it will work in the next update here in afew hours sorry!!

**Comment by Milkbottle98** [comment]
Thanks 😊

**Comment by Andyauk** [comment]
> hello we have fix this it will work in the next update here in afew hours sorry!!

it didn't work sadly. a few of us are trying to work out why. or if we can replace it.

**Comment by Infernalz92** [comment]
Hello, i think that i have fixed that problem and should be pushed in the next update.
