### ISSUE TITLE
character creation does not work

### ISSUE THREAD

**Issue by RexShack** [qbcore-redm-framework/qbr-clothing#6]
when creating a character for the first time you are placed in the world as intended, however when you relog your character does not load : https://www.youtube.com/watch?v=pTBUwZABsJ4

**Comment by RexShack** [comment]
on the latest update the UI is black on black making it hard to change the clothing and skill is still not working / understand you are still working on it but wanted to ensure you were aware.

**Comment by ChatDisabled** [comment]
I know it's been 2 months, but we restarted now with a menu built with react instead of vue. Testing would be appreciated
